### ISSUE TITLE
В @GetMapping(value = "/api/book", params = {"limit", "start"}) limit = "" приходит.

### ISSUE THREAD

**Issue by vienoulis** [StalnoyKapibar/HIB#186]
public BookPageDto getBookDtoByLimitAndAmountAndStart(@RequestParam Map<String, String> params) {
    Pageable pageable = PageRequest.of(Integer.parseInt(params.get("start")),
            Integer.parseInt(params.get("limit")), Sort.by(Sort.Order.asc("id")));
    return bookService.getBookPageByPageable(pageable);
}

**Comment by vienoulis** [comment]
Это при переходе на выбранную категорию.

**Comment by orlovleo12** [comment]
Починили
